export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    light: 2,
    water: 3,
    cover: "/img/monstera.jpeg",
    price: 15,
    description: "jkhcljkschbskcbkbsjchsbvdhjs",
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    light: 3,
    water: 1,
    cover: "/img/lyrata.jpeg",
    price: 16,
  },

  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    light: 1,
    water: 2,
    cover: "/img/pothos.jpeg",
    price: 9,
  },
  {
    name: "calathea",
    category: "classique",
    id: "4kk",
    light: 2,
    water: 3,
    cover: "/img/calathea.jpeg",
    price: 20,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    light: 3,
    water: 1,
    cover: "/img/olivier.jpeg",
    price: 25,
  },

  {
    name: "cactus",
    category: "plante grasse",
    id: "8fp",
    light: 2,
    water: 1,
    cover: "/img/cactus.jpeg",
    price: 6,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    light: 2,
    water: 3,
    cover: "/img/basil.jpeg",
    price: 5,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    light: 2,
    water: 1,
    cover: "/img/succulent.jpeg",
    price: 8,
  },

  {
    name: "menthe",
    category: "extérieur",
    id: "6uo",
    light: 2,
    water: 2,
    cover: "/img/monstera.jpeg",
    price: 4,
  },
];
