export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    isBestSale: true,
    light: 2,
    water: 3,
    price: 15,
    description: "this plant is awesome. You should buy it!!!",
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    light: 3,
    water: 1,
    price: 16,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    light: 1,
    water: 2,
    price: 17,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "yucca",
    category: "classique",
    id: "4kk",
    light: 3,
    water: 1,
    price: 18,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    light: 3,
    water: 1,
    price: 15,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    light: 2,
    water: 2,
    price: 16,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    isBestSale: true,
    light: 2,
    water: 3,
    price: 17,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    light: 2,
    water: 1,
    price: 18,
    description: "this plant is nasty. You should buy it!!!",
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    light: 2,
    water: 1,
    price: 15,
    description: "this plant is nasty. You should buy it!!!",
  },
];
